name: Testing
on:
  workflow_dispatch:
  push:
jobs:
  testCSV:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run test:csv
